name: CI
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install deps
        working-directory: FrontEnd
        run: npm ci

      - name: Typecheck
        working-directory: FrontEnd
        run: npm run typecheck

      - name: Lint
        working-directory: FrontEnd
        run: npm run lint

      - name: Unit tests
        working-directory: FrontEnd
        run: npm test

      - name: Build FrontEnd
        working-directory: FrontEnd
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./FrontEnd
          file: ./FrontEnd/Dockerfile
          push: false

      - name: Trivy scan (filesystem & deps)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: 'FrontEnd'
          format: 'table'
          exit-code: '0'           # don't fail CI on first pass; change to '1' later
          severity: 'CRITICAL,HIGH'

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'frontend-ci:local'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
        env:
          # load the just-built image into the local Docker daemon
          TRIVY_NON_SSL: 'true'
        # buildx kept image in cache; re-build into Docker engine to scan
        # (cheap since layers are cached)
        shell: bash
        run: |
          docker build -t frontend-ci:local -f FrontEnd/Dockerfile FrontEnd
          echo "scanning image…"

      - name: NPM Audit (high+)
        working-directory: FrontEnd
        run: npm run audit
