name: CI
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install deps
        working-directory: FrontEnd
        run: npm ci

      - name: Typecheck
        working-directory: FrontEnd
        run: npm run typecheck

      - name: Lint
        working-directory: FrontEnd
        run: npm run lint

      - name: Unit tests
        working-directory: FrontEnd
        run: npm test

      - name: Build FrontEnd
        working-directory: FrontEnd
        run: npm run build

      # --- Docker sanity build (and load into local engine) ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push, load to local)
        uses: docker/build-push-action@v6
        with:
          context: ./FrontEnd
          file: ./FrontEnd/Dockerfile
          push: false
          load: true                    # <= important: makes image available to 'docker images'
          tags: frontend-ci:local       # <= tag used by Trivy below

      # --- Security scans ---
      - name: Trivy scan (filesystem)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: 'FrontEnd'
          format: 'table'
          exit-code: '0'                # set to '1' later to fail on vulns
          severity: 'CRITICAL,HIGH'

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'frontend-ci:local'
          format: 'table'
          exit-code: '0'                # set to '1' later to enforce
          severity: 'CRITICAL,HIGH'

      - name: NPM Audit (high+)
        working-directory: FrontEnd
        run: npm run audit
